<a href="https://colab.research.google.com/github/EmanSalah2000/cenetriodMinstDataSet/blob/main/Assignment1_SL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier
import math

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()


    8192/11490434 [..............................] - ETA: 0s

In [ ]:
image_index = 3000 # You may select anything up to 60,000
print(y_train[image_index]) # The label is 9
plt.imshow(x_train[image_index], cmap='Greys')

In [ ]:
def cenetroizd(image , grid):
    row, col = image.shape # row*colum
    blocks=[[0 for i in range(grid)] for j in range(grid)]

    row2, col2 = math.ceil(row/grid), math.ceil(col/grid)

    row_copy , colum_copy=0 ,0
   
    
    sum_row_colum=0
    for i in range(grid-1):
        colum_copy=0
        sum_row_colum=sum_row_colum+row2
        for j in range(grid-1):
            blocks[i][j]=[[0 for ee in range(row2)] for rr in range(col2)]
            blocks[i][j]=image[row_copy:row2+row_copy , colum_copy:col2+colum_copy ]
            colum_copy=colum_copy+col2
        row_copy=row_copy+row2

    if (28-sum_row_colum==0):
       sum_row_colum=row2
    else:
      sum_row_colum=28-sum_row_colum
    
    row_copy=0
    for i in range(grid-1):
         blocks[i][grid-1]=[[0 for ee in range(row2)] for rr in range(sum_row_colum)]
         blocks[i][grid-1]=image[row_copy:row2+row_copy , colum_copy:   ]
         row_copy=row_copy+row2
         
    colum_copy=0
    for j in range(grid-1):
         blocks[grid-1][j]=[[0 for ee in range(sum_row_colum)] for rr in range(col2)]
         blocks[grid-1][j]=image[row_copy:  , colum_copy:col2+colum_copy ]
         colum_copy=colum_copy+col2


    blocks[grid-1][grid-1]=[[0 for ee in range(sum_row_colum)] for rr in range(sum_row_colum)]

    blocks[grid-1][grid-1]=image[row_copy:  , colum_copy: ]




    feature_vector=np.zeros((1,(2*grid*grid)))
    count=0
    SumX , SumY , num =0,0,0
 
    
    for a in range(grid):
        for b in range(grid):
          copyarray=blocks[a][b]
          #print(copyarray.shape)
          for i in range(copyarray.shape[0]):
              for j in range(copyarray.shape[1]):
                 SumX=SumX+copyarray[i][j]*i
                 SumY=SumY+copyarray[i][j]*j
                 num=num+copyarray[i][j]
              
          if num!=0 :
             total_xc =SumX / num
             total_yc  = SumY / num
            
             feature_vector[0][count]=total_xc
             feature_vector[0][count+1]=total_yc 
             count=count+2
          else :
               total_xc =0
               total_yc  = 0
               feature_vector[0][count]=total_xc
               feature_vector[0][count+1]=total_yc 
               count=count+2
  
    return feature_vector

In [ ]:
grid=4
counter=0
X_NEWTRAIN=np.zeros([ len(x_train),2*grid*grid])
for i in range(len(x_train)):
      array=np.array(x_train[i])
      X_NEWTRAIN[i]=cenetroizd(array,grid)    
print(X_NEWTRAIN)
print(X_NEWTRAIN.shape)

[[0.         0.         5.97229551 ... 3.04715713 2.7884832  3.04715713]
 [0.         0.         6.         ... 2.75484805 2.79835986 2.75484805]
 [6.         4.56643357 6.         ... 3.76125084 2.44411871 3.76125084]
 ...
 [0.         0.         0.         ... 3.03189951 2.83666185 3.03189951]
 [0.         0.         0.         ... 2.681075   2.85632465 2.681075  ]
 [0.         0.         0.         ... 3.06142447 2.52213193 3.06142447]]
(60000, 32)


In [ ]:
print(X_NEWTRAIN[0])
print(X_NEWTRAIN[0].shape)

[0.         0.         5.97229551 4.6055409  5.77763371 3.49789303
 5.68801898 2.75563464 5.68801898 2.75563464 3.48625209 3.5437075
 3.06227022 3.14568015 3.04014904 3.12592198 3.04014904 3.12592198
 3.17782054 3.26626755 3.20130582 3.04722871 3.20130582 3.04722871
 3.16903512 3.15944062 2.84975095 3.10378411 2.7884832  3.04715713
 2.7884832  3.04715713]
(32,)


In [ ]:
X_NEWTEST=np.zeros([ len(x_test),2*grid*grid])
for i in range(len(x_test)):
    array=np.array(x_test[i])
    X_NEWTEST[i]=cenetroizd(array,grid)   
print(X_NEWTEST)
print(X_NEWTEST.shape)

[[0.         0.         0.         ... 3.32459087 2.50335971 3.32459087]
 [0.         0.         4.56700508 ... 2.8295813  3.16870017 2.79455806]
 [0.         0.         0.         ... 2.99726471 2.98470266 2.99726471]
 ...
 [0.         0.         6.         ... 3.53857206 2.72450481 3.53857206]
 [0.         0.         0.         ... 2.75650439 2.97281524 2.75650439]
 [0.         0.         5.71879699 ... 2.94776851 3.20266297 2.94776851]]
(10000, 32)


In [ ]:
KNN=OneVsRestClassifier(KNeighborsClassifier())
KNN.fit(X_NEWTRAIN,y_train)

OneVsRestClassifier(estimator=KNeighborsClassifier(algorithm='auto',
                                                   leaf_size=30,
                                                   metric='minkowski',
                                                   metric_params=None,
                                                   n_jobs=None, n_neighbors=5,
                                                   p=2, weights='uniform'),
                    n_jobs=None)

In [ ]:
Y_predicted=KNN.predict(X_NEWTEST)
acc=accuracy_score(y_test, Y_predicted)

In [ ]:
print(acc)
# acc in grid=2    0.8418
# acc in grid=3   0.8518 
# acc in grid=4   0.8528
# acc in grid=5   0.8195
# acc in grid=7  0.759



0.8528
